CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE player_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  nickname VARCHAR(64) NOT NULL,
  level INT UNSIGNED NOT NULL DEFAULT 1,
  exp INT UNSIGNED NOT NULL DEFAULT 0,
  avatar VARCHAR(128) NOT NULL DEFAULT 'avatar_001',
  power BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_id (user_id),
  KEY idx_power (power)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE player_assets (
  player_id BIGINT UNSIGNED NOT NULL,
  gold BIGINT UNSIGNED NOT NULL DEFAULT 0,
  diamond BIGINT UNSIGNED NOT NULL DEFAULT 0,
  stamina INT UNSIGNED NOT NULL DEFAULT 0,
  stamina_updated_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE hero_config (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  quality TINYINT NOT NULL,
  role VARCHAR(32) NOT NULL,
  base_hp INT UNSIGNED NOT NULL,
  base_atk INT UNSIGNED NOT NULL,
  base_def INT UNSIGNED NOT NULL,
  power_factor INT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_quality (quality)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE player_hero (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  player_id BIGINT UNSIGNED NOT NULL,
  hero_config_id BIGINT UNSIGNED NOT NULL,
  level INT UNSIGNED NOT NULL DEFAULT 1,
  star INT UNSIGNED NOT NULL DEFAULT 1,
  shard INT UNSIGNED NOT NULL DEFAULT 0,
  locked TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_player_hero (player_id, hero_config_id),
  KEY idx_player_id (player_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO hero_config (id, name, quality, role, base_hp, base_atk, base_def, power_factor)
VALUES
  (1, '孙悟空', 5, '战士', 1200, 260, 110, 120),
  (2, '猪八戒', 4, '坦克', 1500, 180, 160, 110),
  (3, '沙悟净', 3, '守护', 1100, 170, 130, 100),
  (4, '小白龙', 4, '刺客', 980, 240, 90, 115),
  (5, '唐三藏', 3, '辅助', 900, 130, 100, 95);
