/**
 * 设计 token 准源：frontend/stitch/mythic_journey_redux/DESIGN.md（YAML front-matter）。
 * borderRadius 采用 DESIGN.md 原值（不沿用 mini_1 的收紧覆盖与 mini_7 的 full=999px 偏差）。
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#20201f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d0c6ab',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#999077',
        'outline-variant': '#4d4732',
        'surface-tint': '#e9c400',
        primary: '#fff6df',
        'on-primary': '#3a3000',
        'primary-container': '#ffd700',
        'on-primary-container': '#705e00',
        'inverse-primary': '#705d00',
        secondary: '#ffb4a9',
        'on-secondary': '#690002',
        'secondary-container': '#970205',
        'on-secondary-container': '#ff9f92',
        tertiary: '#dbffe6',
        'on-tertiary': '#003921',
        'tertiary-container': '#6ff2ae',
        'on-tertiary-container': '#006d44',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffe16d',
        'primary-fixed-dim': '#e9c400',
        'on-primary-fixed': '#221b00',
        'on-primary-fixed-variant': '#544600',
        'secondary-fixed': '#ffdad5',
        'secondary-fixed-dim': '#ffb4a9',
        'on-secondary-fixed': '#410001',
        'on-secondary-fixed-variant': '#930004',
        'tertiary-fixed': '#78fbb6',
        'tertiary-fixed-dim': '#59de9b',
        'on-tertiary-fixed': '#002111',
        'on-tertiary-fixed-variant': '#005232',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353535',
        'quality-ur': '#FF4500',
        'quality-ssr': '#FFD700',
        'quality-sr': '#DA70D6',
        'quality-r': '#1E90FF',
        'quality-n': '#A9A9A9',
        'ink-wash': '#2D2D2D',
        parchment: '#F5E6BE',
      },
      fontFamily: {
        'display-hero': ['Epilogue', 'sans-serif'],
        'headline-lg': ['Epilogue', 'sans-serif'],
        'headline-lg-mobile': ['Epilogue', 'sans-serif'],
        'title-md': ['Epilogue', 'sans-serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'stats-num': ['"JetBrains Mono"', 'monospace'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'stats-num': ['18px', { lineHeight: '1', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        'stack-xs': '4px',
        'stack-md': '12px',
        'stack-lg': '24px',
      },
    },
  },
  plugins: [],
}
